[package]
name = "sqlmodel-frankensqlite"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "FrankenSQLite (pure-Rust) driver for SQLModel Rust"

[lints]
workspace = true

[dependencies]
sqlmodel-core.workspace = true
asupersync.workspace = true
serde.workspace = true
serde_json.workspace = true
fsqlite = { version = "0.3.7", features = ["async-api"] }
fsqlite-core = "0.3.7"
fsqlite-types = "0.3.7"
fsqlite-error = "0.3.7"

[dev-dependencies]
