//! Every `#[sqlmodel(...)]` field attribute in one model set, on every driver:
//! the DDL it produces, whether introspection reads it back (the schema
//! fixpoint), and what it does at runtime (defaults applied, constraints
//! enforced, generated keys returned, skipped columns left alone, referential
//! actions observed, composite keys usable through the session).
//!
//! Dialect divergences are asserted per dialect and printed; nothing is
//! skipped silently.

use asupersync::Cx;
use serde::{Deserialize, Serialize};
use sqlmodel::prelude::*;
use sqlmodel::{SchemaBuilder, Session};
use sqlmodel_e2e::{DriverUnderTest, OwnedScenario, expect_outcome, run_owned_on_every_driver};
use sqlmodel_schema::diff::schema_diff;
use sqlmodel_schema::{DatabaseSchema, Introspector, ModelTuple};

#[derive(sqlmodel::Model, Debug, Clone, PartialEq)]
#[sqlmodel(table = "e2e_attr_teams")]
struct Team {
    #[sqlmodel(primary_key)]
    id: i64,
    /// `unique` plus a renamed column.
    #[sqlmodel(unique, column = "team_name")]
    name: String,
    /// `nullable` plus a column comment.
    #[sqlmodel(nullable, column_comment = "free text")]
    motto: Option<String>,
    /// A CHECK constraint and a database default.
    #[sqlmodel(column_constraints = ["rating BETWEEN 0 AND 10"], default = "5")]
    rating: i32,
}

#[derive(sqlmodel::Model, Debug, Clone, PartialEq)]
#[sqlmodel(table = "e2e_attr_players")]
struct Player {
    /// Generated by the database.
    #[sqlmodel(primary_key, auto_increment)]
    id: Option<i64>,
    /// Foreign key with both referential actions.
    #[sqlmodel(
        foreign_key = "e2e_attr_teams.id",
        on_delete = "CASCADE",
        on_update = "CASCADE"
    )]
    team_id: i64,
    /// Named index plus an explicit SQL type.
    #[sqlmodel(index = "e2e_attr_players_name_idx", sql_type = "VARCHAR(40)")]
    name: String,
    /// The database owns this column entirely.
    #[sqlmodel(skip_insert, skip_update, default = "0")]
    score: i32,
    /// Written once, never updated.
    #[sqlmodel(skip_update)]
    created_by: String,
    /// Nullable foreign key with SET NULL.
    #[sqlmodel(nullable, foreign_key = "e2e_attr_teams.id", on_delete = "SET NULL")]
    mentor_team_id: Option<i64>,
}

/// Composite primary key, both parts foreign keys.
#[derive(sqlmodel::Model, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[sqlmodel(table = "e2e_attr_memberships")]
struct Membership {
    #[sqlmodel(primary_key, foreign_key = "e2e_attr_teams.id", on_delete = "CASCADE")]
    team_id: i64,
    #[sqlmodel(
        primary_key,
        foreign_key = "e2e_attr_players.id",
        on_delete = "CASCADE"
    )]
    player_id: i64,
    role: String,
}

async fn count<C: Connection>(cx: &Cx, conn: &C, table: &str, label: &str) -> i64 {
    let rows = expect_outcome(
        conn.query(cx, &format!("SELECT COUNT(*) FROM {table}"), &[])
            .await,
        label,
    );
    rows[0].get_as::<i64>(0).expect("count")
}

async fn introspect_ours<C: Connection>(
    cx: &Cx,
    conn: &C,
    dialect: Dialect,
    names: &[&str],
    label: &str,
) -> DatabaseSchema {
    let introspector = Introspector::new(dialect);
    let present = expect_outcome(
        introspector.table_names(cx, conn).await,
        &format!("{label}: table_names"),
    );
    let mut schema = DatabaseSchema::new(dialect);
    for name in names {
        if present.iter().any(|t| t == name) {
            let info = expect_outcome(
                introspector.table_info(cx, conn, name).await,
                &format!("{label}: table_info {name}"),
            );
            schema.tables.insert((*name).to_string(), info);
        }
    }
    schema
}

struct Attributes;

impl OwnedScenario for Attributes {
    async fn run<C: Connection + 'static>(&self, cx: &Cx, conn: C, driver: &DriverUnderTest) {
        let d = driver.name();
        let dialect = driver.dialect();
        let q = |name: &str| dialect.quote_identifier(name);
        let teams = q(<Team as Model>::TABLE_NAME);
        let players = q(<Player as Model>::TABLE_NAME);
        let memberships = q(<Membership as Model>::TABLE_NAME);
        let ours = [
            <Team as Model>::TABLE_NAME,
            <Player as Model>::TABLE_NAME,
            <Membership as Model>::TABLE_NAME,
        ];

        for t in [&memberships, &players, &teams] {
            expect_outcome(
                conn.execute(cx, &format!("DROP TABLE IF EXISTS {t}"), &[])
                    .await,
                &format!("{d}: drop stale {t}"),
            );
        }
        if dialect == Dialect::Sqlite {
            expect_outcome(
                conn.execute(cx, "PRAGMA foreign_keys = ON", &[]).await,
                &format!("{d}: enable foreign keys"),
            );
        }

        // 1. DDL for every attribute, printed so a failure shows the statement.
        for stmt in SchemaBuilder::new()
            .dialect(dialect)
            .create_table::<Team>()
            .create_table::<Player>()
            .create_table::<Membership>()
            .build()
        {
            eprintln!("{d}: ddl: {stmt}");
            expect_outcome(
                conn.execute(cx, &stmt, &[]).await,
                &format!("{d}: ddl `{stmt}`"),
            );
        }

        // 2. Introspection reads every attribute back: the fixpoint holds.
        let expected = <(Team, Player, Membership) as ModelTuple>::database_schema(dialect);
        let current = introspect_ours(cx, &conn, dialect, &ours, &format!("{d}: introspect")).await;
        let diff = schema_diff(&current, &expected);
        assert!(
            diff.operations.is_empty(),
            "{d}: every attribute must survive introspection; leftover operations: {:#?}",
            diff.operations
        );
        let motto = current.tables[<Team as Model>::TABLE_NAME]
            .columns
            .iter()
            .find(|c| c.name == "motto")
            .expect("motto column");
        match dialect {
            Dialect::Sqlite => {
                eprintln!("{d}: column comments are not a SQLite feature (introspected as none)");
                assert_eq!(motto.comment, None, "{d}");
            }
            Dialect::Postgres | Dialect::Mysql => {
                assert_eq!(
                    motto.comment.as_deref(),
                    Some("free text"),
                    "{d}: column comment"
                );
            }
        }
        let teams_info = &current.tables[<Team as Model>::TABLE_NAME];
        assert!(
            teams_info
                .unique_constraints
                .iter()
                .any(|u| u.columns == ["team_name"]),
            "{d}: unique on the renamed column: {:?}",
            teams_info.unique_constraints
        );
        let players_info = &current.tables[<Player as Model>::TABLE_NAME];
        assert!(
            players_info
                .indexes
                .iter()
                .any(|i| i.name == "e2e_attr_players_name_idx"),
            "{d}: named index: {:?}",
            players_info.indexes
        );
        let fk = players_info
            .foreign_keys
            .iter()
            .find(|f| f.column == "team_id")
            .expect("team_id fk");
        assert_eq!(
            fk.on_delete.as_deref().map(str::to_ascii_uppercase),
            Some("CASCADE".to_string()),
            "{d}: ON DELETE CASCADE"
        );
        assert_eq!(
            current.tables[<Membership as Model>::TABLE_NAME].primary_key,
            vec!["team_id".to_string(), "player_id".to_string()],
            "{d}: composite primary key"
        );

        // 3. Behavior.
        // default: a row inserted without `rating` gets 5.
        expect_outcome(
            conn.execute(
                cx,
                &format!(
                    "INSERT INTO {teams} ({}, {}) VALUES (1, 'red')",
                    q("id"),
                    q("team_name")
                ),
                &[],
            )
            .await,
            &format!("{d}: insert team without rating"),
        );
        let rating = expect_outcome(
            conn.query(
                cx,
                &format!("SELECT {} FROM {teams} WHERE {} = 1", q("rating"), q("id")),
                &[],
            )
            .await,
            &format!("{d}: read rating"),
        );
        assert_eq!(
            rating[0].get_as::<i64>(0).unwrap(),
            5,
            "{d}: DEFAULT applied"
        );
        // unique: same team name again is refused.
        assert!(
            matches!(
                insert!(&Team {
                    id: 2,
                    name: "red".into(),
                    motto: None,
                    rating: 3
                })
                .execute(cx, &conn)
                .await,
                Outcome::Err(Error::Query(_))
            ),
            "{d}: UNIQUE enforced"
        );
        // check: rating 11 is refused.
        assert!(
            matches!(
                insert!(&Team {
                    id: 2,
                    name: "blue".into(),
                    motto: Some("go".into()),
                    rating: 11
                })
                .execute(cx, &conn)
                .await,
                Outcome::Err(Error::Query(_))
            ),
            "{d}: CHECK enforced"
        );
        expect_outcome(
            insert!(&Team {
                id: 2,
                name: "blue".into(),
                motto: Some("go".into()),
                rating: 7
            })
            .execute(cx, &conn)
            .await,
            &format!("{d}: insert blue"),
        );

        // auto_increment: generated ids come back; skip_insert leaves score to the default.
        let first = expect_outcome(
            insert!(&Player {
                id: None,
                team_id: 1,
                name: "ann".into(),
                score: 99,
                created_by: "seed".into(),
                mentor_team_id: Some(2),
            })
            .execute(cx, &conn)
            .await,
            &format!("{d}: insert player 1"),
        );
        let second = expect_outcome(
            insert!(&Player {
                id: None,
                team_id: 1,
                name: "bob".into(),
                score: 99,
                created_by: "seed".into(),
                mentor_team_id: None,
            })
            .execute(cx, &conn)
            .await,
            &format!("{d}: insert player 2"),
        );
        assert!(
            first > 0 && second == first + 1,
            "{d}: generated ids {first}, {second}"
        );
        let stored: Player = expect_outcome(
            select!(Player)
                .filter(Expr::col("id").eq(first))
                .one(cx, &conn)
                .await,
            &format!("{d}: read player 1"),
        );
        assert_eq!(
            stored.score, 0,
            "{d}: skip_insert column took the DEFAULT, not 99"
        );
        assert_eq!(stored.created_by, "seed", "{d}");

        // skip_update: name changes, score and created_by do not.
        let updated = expect_outcome(
            update!(&Player {
                id: Some(first),
                team_id: 1,
                name: "ann-renamed".into(),
                score: 42,
                created_by: "someone-else".into(),
                mentor_team_id: Some(2),
            })
            .execute(cx, &conn)
            .await,
            &format!("{d}: update player 1"),
        );
        assert_eq!(updated, 1, "{d}");
        let stored: Player = expect_outcome(
            select!(Player)
                .filter(Expr::col("id").eq(first))
                .one(cx, &conn)
                .await,
            &format!("{d}: re-read player 1"),
        );
        assert_eq!(stored.name, "ann-renamed", "{d}");
        assert_eq!(stored.score, 0, "{d}: skip_update column untouched");
        assert_eq!(
            stored.created_by, "seed",
            "{d}: skip_update column untouched"
        );

        // composite primary key through the session.
        let mut s = Session::new(conn);
        s.add(&Membership {
            team_id: 1,
            player_id: first,
            role: "captain".into(),
        });
        expect_outcome(s.commit(cx).await, &format!("{d}: commit membership"));
        let found: Option<Membership> = expect_outcome(
            s.get_by_pk(cx, &[Value::from(1i64), Value::from(first)])
                .await,
            &format!("{d}: get_by_pk composite"),
        );
        assert_eq!(found.map(|m| m.role), Some("captain".to_string()), "{d}");
        let conn = s.into_connection();

        // on_delete SET NULL: deleting the mentor team clears mentor_team_id.
        expect_outcome(
            conn.execute(
                cx,
                &format!("DELETE FROM {teams} WHERE {} = 2", q("id")),
                &[],
            )
            .await,
            &format!("{d}: delete mentor team"),
        );
        let stored: Player = expect_outcome(
            select!(Player)
                .filter(Expr::col("id").eq(first))
                .one(cx, &conn)
                .await,
            &format!("{d}: read player after SET NULL"),
        );
        assert_eq!(stored.mentor_team_id, None, "{d}: ON DELETE SET NULL");

        // on_delete CASCADE: deleting team 1 removes its players and memberships.
        expect_outcome(
            conn.execute(
                cx,
                &format!("DELETE FROM {teams} WHERE {} = 1", q("id")),
                &[],
            )
            .await,
            &format!("{d}: delete team 1"),
        );
        assert_eq!(
            count(cx, &conn, &players, "players after cascade").await,
            0,
            "{d}"
        );
        assert_eq!(
            count(cx, &conn, &memberships, "memberships after cascade").await,
            0,
            "{d}"
        );

        for t in [&memberships, &players, &teams] {
            expect_outcome(
                conn.execute(cx, &format!("DROP TABLE {t}"), &[]).await,
                &format!("{d}: drop {t}"),
            );
        }
    }
}

#[test]
fn every_field_attribute_works_on_every_available_driver() {
    let cx = Cx::for_testing();
    let ran = run_owned_on_every_driver(&cx, &Attributes);
    assert!(ran.contains(&"frankensqlite"), "{ran:?}");
    assert!(ran.contains(&"c-sqlite(memory)"), "{ran:?}");
}
