-- op: ddl_players
-- dialect: postgres
CREATE TABLE IF NOT EXISTS "players" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "team_id" BIGINT NOT NULL,
    "name" VARCHAR(40) NOT NULL,
    "score" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL,
    "weight" DOUBLE PRECISION,
  CONSTRAINT "fk_players_team_id" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "players_name_idx" ON "players" ("name")
-- params: []
